In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\arpit\Downloads\Zomato-data-.csv")

In [6]:
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [7]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [8]:
df.tail()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [9]:
df.sample()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
146,Darbar,No,No,3.0/5,98,800,Dining

In [10]:
df.sample()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
65,Kabab Magic,Yes,No,4.1/5,1720,400,Dining

In [11]:
df.shape # Row and Column

(148, 7)

In [12]:
df.dtypes

name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
approx_cost(for two people)     int64
listed_in(type)                object
dtype: object

In [13]:
df.sample(5)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
87,Krishna Sagar,No,No,3.5/5,31,200,Dining
32,Sweet Truth,Yes,No,3.9/5,35,500,Dining
143,Melting Melodies,No,No,3.3/5,0,100,Dining
96,Kaggis,No,No,3.8/5,64,250,Dining
119,K27 - The Pub,No,No,3.1/5,30,900,Dining

In [14]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

In [16]:
df.describe()

             votes  approx_cost(for two people)
count   148.000000                   148.000000
mean    264.810811                   418.243243
std     653.676951                   223.085098
min       0.000000                   100.000000
25%       6.750000                   200.000000
50%      43.500000                   400.000000
75%     221.750000                   600.000000
max    4884.000000                   950.000000

In [17]:
df[["name","online_order"]]

                      name online_order
0                    Jalsa          Yes
1           Spice Elephant          Yes
2          San Churro Cafe          Yes
3    Addhuri Udupi Bhojana           No
4            Grand Village           No
..                     ...          ...
143       Melting Melodies           No
144        New Indraprasta           No
145           Anna Kuteera          Yes
146                 Darbar           No
147          Vijayalakshmi          Yes

[148 rows x 2 columns]

In [23]:
df["name"]

0                      Jalsa
1             Spice Elephant
2            San Churro Cafe
3      Addhuri Udupi Bhojana
4              Grand Village
               ...
143         Melting Melodies
144          New Indraprasta
145             Anna Kuteera
146                   Darbar
147            Vijayalakshmi
Name: name, Length: 148, dtype: object

In [43]:
print(df["rate"].dtype)

float64

In [44]:
df = pd.read_csv(r"C:\Users\arpit\Downloads\Zomato-data-.csv")

In [45]:
df["rate"]= df["rate"].astype(str).str.split('/')

In [46]:
df["rate"]= pd.to_numeric(df["rate"], errors= 'coerce')

In [47]:
df[df["rate"] > 3.8] #single condition

Empty DataFrame
Columns: [name, online_order, book_table, rate, votes, approx_cost(for two people), listed_in(type)]
Index: []

In [51]:
df[(df['listed_in(type)']== 'Dining') & (df['book_table'] == 'Yes')]

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
61,Goa 0 Km,Yes,Yes,NaN,163,800,Dining
63,Jeet Restaurant,No,Yes,NaN,808,850,Dining

In [54]:
df.sort_values("votes", ascending = False)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
38,Empire Restaurant,Yes,No,NaN,4884,750,other
86,Meghana Foods,Yes,No,NaN,4401,600,Dining
7,Onesta,Yes,Yes,NaN,2556,600,Cafes
44,Onesta,Yes,Yes,NaN,2556,600,other
65,Kabab Magic,Yes,No,NaN,1720,400,Dining
...,...,...,...,...,...,...,...
117,Kulfi & More,No,No,NaN,0,150,Dining
118,Kannadigas Karavali,No,No,NaN,0,250,Dining
125,Soms Kitchen & Bakes,No,No,NaN,0,400,Dining
126,Banashankari Nati Style,No,No,NaN,0,350,Dining
110,Hari Super Sandwich,No,No,NaN,0,200,Dining

df.rename(columns = {"name" : "customer_name"}, inplace = true)